version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bixi_finder
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpacker:
      build: .
      command: ./bin/webpack-dev-server
      volumes:
        - .:/bixi_finder
      ports:
        - '3035:3035'
